services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce
    volumes:
      - data:/var/lib/postgresql/data
      - .docker/:/database/

volumes:
  data:
